
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AIMS_MEAL_TYPE](
	[MEAL_TYPE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[MAIL_TYPE] [varchar](50) NULL,
	[MEAL_TYPE_DESC] [varchar](250) NULL,
 CONSTRAINT [PK_AIMS_MEAL_TYPE] PRIMARY KEY CLUSTERED 
(
	[MEAL_TYPE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

