alter table AIMS_ACCOMODATION
add Currency varchar(50)


alter proc AIMS_ACCOMODATION_ADD      
@Accomodation varchar(50),      
@GuestName varchar(50),      
@GuestRefNo varchar(50),      
@GuestNoOfRooms varchar(50),      
@GuestArrivalDate varchar(50),     
@GuestFlightArrivalTime varchar(50),    
@GuestDepartDate varchar(50),    
@GuestAimsSettle varchar(50),      
@GuestCountryOfRegion varchar(50),      
@Religion varchar(50),      
@DiabeticMeals varchar(50),      
@BedAndBreakFast varchar(50),      
@Meals varchar(50),      
@Laundry varchar(50),      
@Telephone varchar(50),      
@MiniBar varchar(50),      
@SpecialRequest varchar(50),      
@PatientID varchar(50),      
@UserID varchar(50),      
@AccomodationLetter varchar(1000),  
@ContactTelMobileNo varchar(50),      
@ContactEmailAddress varchar(50),      
@DOB varchar(50),      
@NoOfGuests varchar(50),      
@RoomRatePerNight varchar(50),      
@RoomType varchar(50),      
@MealBreakFast varchar(50),      
@MealBreakLunch varchar(50),      
@MealBreakDinner varchar(50),      
@MealBreakFullBoard varchar(50),      
@SocialTransport varchar(50),      
@AdditionalNotes varchar(250),
      @currency varchar(250)
as       
begin      
insert into aims_accomodation (      
SUPPLIER_ID,      
GUEST_NAME,      
GUEST_REF_NO,      
GUEST_NO_OF_ROOMS,      
GUEST_ARRIVAL_DATE,      
GUEST_FLIGHT_ARRIVAL_DATE,      
GUEST_DEPART_DATE,      
GUEST_AIMS_SETTLE,      
GUEST_COUNTRY_OF_ORIGIN,      
GUEST_RELIGION,      
GUEST_DIABETIC_MEALS,      
GUEST_BED_AND_BREAKFAST,      
GUEST_MEALS,      
GUEST_LAUNDRY,      
GUEST_TELEPHONE,      
GUEST_MINIBAR,      
GUEST_SPECIAL_REQUEST,      
PATIENT_ID,      
CREATED_BY,      
ACCOMODATION_LETTER,  
ContactTelMobileNo,  
ContactEmailAddress,  
DOB,  
NoOfGuests,  
RoomRatePerNight,  
RoomType,  
MealBreakFast,  
MealBreakLunch,  
MealBreakDinner,  
MealBreakFullBoard,  
SocialTransport,  
AdditionalNotes,currency  
) VALUES(      
@Accomodation  ,      
@GuestName  ,      
@GuestRefNo  ,      
@GuestNoOfRooms  ,      
@GuestArrivalDate ,      
@GuestFlightArrivalTime ,      
@GuestDepartDate ,      
@GuestAimsSettle  ,      
@GuestCountryOfRegion  ,      
@Religion  ,      
@DiabeticMeals  ,      
@BedAndBreakFast  ,      
@Meals  ,      
@Laundry  ,      
@Telephone  ,      
@MiniBar  ,      
@SpecialRequest  ,      
@PatientID  ,      
@UserID  ,      
@AccomodationLetter,  
@ContactTelMobileNo,  
@ContactEmailAddress,  
@DOB,  
@NoOfGuests,  
@RoomRatePerNight,  
@RoomType,  
@MealBreakFast,  
@MealBreakLunch,  
@MealBreakDinner,  
@MealBreakFullBoard,  
@SocialTransport,  
@AdditionalNotes,@Currency        
)        
end