SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AIMS_ACCOMODATION](
	[ACCOMODATION_BOOKING_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SUPPLIER_ID] [numeric](18, 0) NULL,
	[GUEST_NAME] [varchar](250) NULL,
	[GUEST_REF_NO] [varchar](50) NULL,
	[GUEST_NO_OF_ROOMS] [varchar](50) NULL,
	[GUEST_ARRIVAL_DATE] [varchar](50) NULL,
	[GUEST_FLIGHT_ARRIVAL_DATE] [varchar](50) NULL,
	[GUEST_DEPART_DATE] [varchar](50) NULL,
	[GUEST_AIMS_SETTLE] [varchar](50) NULL,
	[GUEST_COUNTRY_OF_ORIGIN] [numeric](18, 0) NULL,
	[GUEST_RELIGION] [numeric](18, 0) NULL,
	[GUEST_DIABETIC_MEALS] [varchar](250) NULL,
	[GUEST_BED_AND_BREAKFAST] [varchar](250) NULL,
	[GUEST_MEALS] [varchar](50) NULL,
	[GUEST_LAUNDRY] [varchar](50) NULL,
	[GUEST_TELEPHONE] [varchar](50) NULL,
	[GUEST_MINIBAR] [varchar](50) NULL,
	[GUEST_SPECIAL_REQUEST] [varchar](250) NULL,
	[PATIENT_ID] [numeric](18, 0) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[ACCOMODATION_LETTER] [varchar](1000) NULL,
	[CREATION_DTTM] [datetime] NULL,
	[ContactTelMobileNo] [varchar](50) NULL,
	[ContactEmailAddress] [varchar](50) NULL,
	[DOB] [varchar](50) NULL,
	[NoOfGuests] [varchar](50) NULL,
	[RoomRatePerNight] [varchar](50) NULL,
	[RoomType] [numeric](18, 0) NULL,
	[MealBreakFast] [varchar](50) NULL,
	[MealBreakLunch] [varchar](50) NULL,
	[MealBreakDinner] [varchar](50) NULL,
	[MealBreakFullBoard] [varchar](50) NULL,
	[SocialTransport] [varchar](50) NULL,
	[AdditionalNotes] [varchar](250) NULL,
 CONSTRAINT [PK_AIMS_ACCOMODATION] PRIMARY KEY CLUSTERED 
(
	[ACCOMODATION_BOOKING_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AIMS_ACCOMODATION]  WITH CHECK ADD  CONSTRAINT [FK_AIMS_ACCOMODATION_AIMS_ACCOMODATION] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[AIMS_PATIENT] ([PATIENT_ID])
GO

ALTER TABLE [dbo].[AIMS_ACCOMODATION] CHECK CONSTRAINT [FK_AIMS_ACCOMODATION_AIMS_ACCOMODATION]
GO

ALTER TABLE [dbo].[AIMS_ACCOMODATION]  WITH CHECK ADD  CONSTRAINT [FK_AIMS_ACCOMODATION_AIMS_SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[AIMS_SUPPLIER] ([SUPPLIER_ID])
GO

ALTER TABLE [dbo].[AIMS_ACCOMODATION] CHECK CONSTRAINT [FK_AIMS_ACCOMODATION_AIMS_SUPPLIER]
GO

ALTER TABLE [dbo].[AIMS_ACCOMODATION] ADD  CONSTRAINT [DF_AIMS_ACCOMODATION_CREATION_DTTM]  DEFAULT (getdate()) FOR [CREATION_DTTM]
GO



select * from [AIMS_ACCOMODATION] 