GO

/****** Object:  Table [dbo].[AIMS_GOP_USER_LIMIT]    Script Date: 02/25/2019 20:53:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AIMS_GOP_USER_LIMIT](
	[LIMIT_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[USER_NAME] [varchar](50) NOT NULL,
	[LIMIT] [money] NULL,
 CONSTRAINT [PK_AIMS_AUTH_MATRIX_1] PRIMARY KEY CLUSTERED 
(
	[LIMIT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AIMS_GOP_USER_LIMIT]  WITH CHECK ADD  CONSTRAINT [FK_AIMS_GOP_USER_LIMIT_AIMS_USERS] FOREIGN KEY([USER_NAME])
REFERENCES [dbo].[AIMS_USERS] ([User_Name])
GO

ALTER TABLE [dbo].[AIMS_GOP_USER_LIMIT] CHECK CONSTRAINT [FK_AIMS_GOP_USER_LIMIT_AIMS_USERS]
GO

