delete from aims_currency
insert into aims_currency values ('ÅLAND ISLANDS','Euro','EUR','978')
insert into aims_currency values ('ZIMBABWE','Zimbabwe Dollar','ZWL','932')
insert into aims_currency values ('ZAMBIA','Zambian Kwacha','ZMW','967')
insert into aims_currency values ('YEMEN','Yemeni Rial','YER','886')
insert into aims_currency values ('WESTERN SAHARA','Moroccan Dirham','MAD','504')
insert into aims_currency values ('WALLIS AND FUTUNA','CFP Franc','XPF','953')
insert into aims_currency values ('VIRGIN ISLANDS (U.S.)','US Dollar','USD','840')
insert into aims_currency values ('VIRGIN ISLANDS (BRITISH)','US Dollar','USD','840')
insert into aims_currency values ('VIET NAM','Dong','VND','704')
insert into aims_currency values ('VENEZUELA (BOLIVARIAN REPUBLIC OF)','Bolivar','VEF','937')
insert into aims_currency values ('VANUATU','Vatu','VUV','548')
insert into aims_currency values ('UZBEKISTAN','Uzbekistan Sum','UZS','860')
insert into aims_currency values ('URUGUAY','Uruguay Peso en Unidades Indexadas (URUIURUI)','UYI','940')
insert into aims_currency values ('URUGUAY','Peso Uruguayo','UYU','858')
insert into aims_currency values ('UNITED STATES OF AMERICA (THE)','US Dollar','USD','840')
insert into aims_currency values ('UNITED STATES OF AMERICA (THE)','US Dollar (Next day)','USN','997')
insert into aims_currency values ('UNITED STATES MINOR OUTLYING ISLANDS (THE)','US Dollar','USD','840')
insert into aims_currency values ('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)','Pound Sterling','GBP','826')
insert into aims_currency values ('UNITED ARAB EMIRATES (THE)','UAE Dirham','AED','784')
insert into aims_currency values ('UKRAINE','Hryvnia','UAH','980')
insert into aims_currency values ('UGANDA','Uganda Shilling','UGX','800')
insert into aims_currency values ('TUVALU','Australian Dollar','AUD','36')
insert into aims_currency values ('TURKS AND CAICOS ISLANDS (THE)','US Dollar','USD','840')
insert into aims_currency values ('TURKMENISTAN','Turkmenistan New Manat','TMT','934')
insert into aims_currency values ('TURKEY','Turkish Lira','TRY','949')
insert into aims_currency values ('TUNISIA','Tunisian Dinar','TND','788')
insert into aims_currency values ('TRINIDAD AND TOBAGO','Trinidad and Tobago Dollar','TTD','780')
insert into aims_currency values ('TONGA','Pa’anga','TOP','776')
insert into aims_currency values ('TOKELAU','New Zealand Dollar','NZD','554')
insert into aims_currency values ('TOGO','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('TIMOR-LESTE','US Dollar','USD','840')
insert into aims_currency values ('THAILAND','Baht','THB','764')
insert into aims_currency values ('TANZANIA, UNITED REPUBLIC OF','Tanzanian Shilling','TZS','834')
insert into aims_currency values ('TAJIKISTAN','Somoni','TJS','972')
insert into aims_currency values ('TAIWAN (PROVINCE OF CHINA)','New Taiwan Dollar','TWD','901')
insert into aims_currency values ('SYRIAN ARAB REPUBLIC','Syrian Pound','SYP','760')
insert into aims_currency values ('SWITZERLAND','WIR Euro','CHE','947')
insert into aims_currency values ('SWITZERLAND','Swiss Franc','CHF','756')
insert into aims_currency values ('SWITZERLAND','WIR Franc','CHW','948')
insert into aims_currency values ('SWEDEN','Swedish Krona','SEK','752')
insert into aims_currency values ('SWAZILAND','Lilangeni','SZL','748')
insert into aims_currency values ('SVALBARD AND JAN MAYEN','Norwegian Krone','NOK','578')
insert into aims_currency values ('SURINAME','Surinam Dollar','SRD','968')
insert into aims_currency values ('SUDAN (THE)','Sudanese Pound','SDG','938')
insert into aims_currency values ('SRI LANKA','Sri Lanka Rupee','LKR','144')
insert into aims_currency values ('SPAIN','Euro','EUR','978')
insert into aims_currency values ('SOUTH SUDAN','South Sudanese Pound','SSP','728')
insert into aims_currency values ('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','No universal currency','','')
insert into aims_currency values ('SOUTH AFRICA','Rand','ZAR','710')
insert into aims_currency values ('SOMALIA','Somali Shilling','SOS','706')
insert into aims_currency values ('SOLOMON ISLANDS','Solomon Islands Dollar','SBD','90')
insert into aims_currency values ('SLOVENIA','Euro','EUR','978')
insert into aims_currency values ('SLOVAKIA','Euro','EUR','978')
insert into aims_currency values ('SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"','Sucre','XSU','994')
insert into aims_currency values ('SINT MAARTEN (DUTCH PART)','Netherlands Antillean Guilder','ANG','532')
insert into aims_currency values ('SINGAPORE','Singapore Dollar','SGD','702')
insert into aims_currency values ('SIERRA LEONE','Leone','SLL','694')
insert into aims_currency values ('SEYCHELLES','Seychelles Rupee','SCR','690')
insert into aims_currency values ('SERBIA','Serbian Dinar','RSD','941')
insert into aims_currency values ('SENEGAL','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('SAUDI ARABIA','Saudi Riyal','SAR','682')
insert into aims_currency values ('SAO TOME AND PRINCIPE','Dobra','STN','930')
insert into aims_currency values ('SAN MARINO','Euro','EUR','978')
insert into aims_currency values ('SAMOA','Tala','WST','882')
insert into aims_currency values ('SAINT VINCENT AND THE GRENADINES','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('SAINT PIERRE AND MIQUELON','Euro','EUR','978')
insert into aims_currency values ('SAINT MARTIN (FRENCH PART)','Euro','EUR','978')
insert into aims_currency values ('SAINT LUCIA','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('SAINT KITTS AND NEVIS','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','Saint Helena Pound','SHP','654')
insert into aims_currency values ('SAINT BARTHÉLEMY','Euro','EUR','978')
insert into aims_currency values ('RÉUNION','Euro','EUR','978')
insert into aims_currency values ('RWANDA','Rwanda Franc','RWF','646')
insert into aims_currency values ('RUSSIAN FEDERATION (THE)','Russian Ruble','RUB','643')
insert into aims_currency values ('ROMANIA','Romanian Leu','RON','946')
insert into aims_currency values ('QATAR','Qatari Rial','QAR','634')
insert into aims_currency values ('PUERTO RICO','US Dollar','USD','840')
insert into aims_currency values ('PORTUGAL','Euro','EUR','978')
insert into aims_currency values ('POLAND','Zloty','PLN','985')
insert into aims_currency values ('PITCAIRN','New Zealand Dollar','NZD','554')
insert into aims_currency values ('PHILIPPINES (THE)','Philippine Peso','PHP','608')
insert into aims_currency values ('PERU','Nuevo Sol','PEN','604')
insert into aims_currency values ('PARAGUAY','Guarani','PYG','600')
insert into aims_currency values ('PAPUA NEW GUINEA','Kina','PGK','598')
insert into aims_currency values ('PANAMA','Balboa','PAB','590')
insert into aims_currency values ('PANAMA','US Dollar','USD','840')
insert into aims_currency values ('PALESTINE, STATE OF','No universal currency','','')
insert into aims_currency values ('PALAU','US Dollar','USD','840')
insert into aims_currency values ('PAKISTAN','Pakistan Rupee','PKR','586')
insert into aims_currency values ('OMAN','Rial Omani','OMR','512')
insert into aims_currency values ('NORWAY','Norwegian Krone','NOK','578')
insert into aims_currency values ('NORTHERN MARIANA ISLANDS (THE)','US Dollar','USD','840')
insert into aims_currency values ('NORFOLK ISLAND','Australian Dollar','AUD','36')
insert into aims_currency values ('NIUE','New Zealand Dollar','NZD','554')
insert into aims_currency values ('NIGERIA','Naira','NGN','566')
insert into aims_currency values ('NIGER (THE)','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('NICARAGUA','Cordoba Oro','NIO','558')
insert into aims_currency values ('NEW ZEALAND','New Zealand Dollar','NZD','554')
insert into aims_currency values ('NEW CALEDONIA','CFP Franc','XPF','953')
insert into aims_currency values ('NETHERLANDS (THE)','Euro','EUR','978')
insert into aims_currency values ('NEPAL','Nepalese Rupee','NPR','524')
insert into aims_currency values ('NAURU','Australian Dollar','AUD','36')
insert into aims_currency values ('NAMIBIA','Namibia Dollar','NAD','516')
insert into aims_currency values ('NAMIBIA','Rand','ZAR','710')
insert into aims_currency values ('MYANMAR','Kyat','MMK','104')
insert into aims_currency values ('MOZAMBIQUE','Mozambique Metical','MZN','943')
insert into aims_currency values ('MOROCCO','Moroccan Dirham','MAD','504')
insert into aims_currency values ('MONTSERRAT','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('MONTENEGRO','Euro','EUR','978')
insert into aims_currency values ('MONGOLIA','Tugrik','MNT','496')
insert into aims_currency values ('MONACO','Euro','EUR','978')
insert into aims_currency values ('MOLDOVA (THE REPUBLIC OF)','Moldovan Leu','MDL','498')
insert into aims_currency values ('MICRONESIA (FEDERATED STATES OF)','US Dollar','USD','840')
insert into aims_currency values ('MEXICO','Mexican Peso','MXN','484')
insert into aims_currency values ('MEXICO','Mexican Unidad de Inversion (UDI)','MXV','979')
insert into aims_currency values ('MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP','ADB Unit of Account','XUA','965')
insert into aims_currency values ('MAYOTTE','Euro','EUR','978')
insert into aims_currency values ('MAURITIUS','Mauritius Rupee','MUR','480')
insert into aims_currency values ('MAURITANIA','Ouguiya','MRU','929')
insert into aims_currency values ('MARTINIQUE','Euro','EUR','978')
insert into aims_currency values ('MARSHALL ISLANDS (THE)','US Dollar','USD','840')
insert into aims_currency values ('MALTA','Euro','EUR','978')
insert into aims_currency values ('MALI','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('MALDIVES','Rufiyaa','MVR','462')
insert into aims_currency values ('MALAYSIA','Malaysian Ringgit','MYR','458')
insert into aims_currency values ('MALAWI','Kwacha','MWK','454')
insert into aims_currency values ('MADAGASCAR','Malagasy Ariary','MGA','969')
insert into aims_currency values ('MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)','Denar','MKD','807')
insert into aims_currency values ('MACAO','Pataca','MOP','446')
insert into aims_currency values ('LUXEMBOURG','Euro','EUR','978')
insert into aims_currency values ('LITHUANIA','Euro','EUR','978')
insert into aims_currency values ('LIECHTENSTEIN','Swiss Franc','CHF','756')
insert into aims_currency values ('LIBYA','Libyan Dinar','LYD','434')
insert into aims_currency values ('LIBERIA','Liberian Dollar','LRD','430')
insert into aims_currency values ('LESOTHO','Loti','LSL','426')
insert into aims_currency values ('LESOTHO','Rand','ZAR','710')
insert into aims_currency values ('LEBANON','Lebanese Pound','LBP','422')
insert into aims_currency values ('LATVIA','Euro','EUR','978')
insert into aims_currency values ('LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)','Kip','LAK','418')
insert into aims_currency values ('KYRGYZSTAN','Som','KGS','417')
insert into aims_currency values ('KUWAIT','Kuwaiti Dinar','KWD','414')
insert into aims_currency values ('KOREA (THE REPUBLIC OF)','Won','KRW','410')
insert into aims_currency values ('KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)','North Korean Won','KPW','408')
insert into aims_currency values ('KIRIBATI','Australian Dollar','AUD','36')
insert into aims_currency values ('KENYA','Kenyan Shilling','KES','404')
insert into aims_currency values ('KAZAKHSTAN','Tenge','KZT','398')
insert into aims_currency values ('JORDAN','Jordanian Dinar','JOD','400')
insert into aims_currency values ('JERSEY','Pound Sterling','GBP','826')
insert into aims_currency values ('JAPAN','Yen','JPY','392')
insert into aims_currency values ('JAMAICA','Jamaican Dollar','JMD','388')
insert into aims_currency values ('ITALY','Euro','EUR','978')
insert into aims_currency values ('ISRAEL','New Israeli Sheqel','ILS','376')
insert into aims_currency values ('ISLE OF MAN','Pound Sterling','GBP','826')
insert into aims_currency values ('IRELAND','Euro','EUR','978')
insert into aims_currency values ('IRAQ','Iraqi Dinar','IQD','368')
insert into aims_currency values ('IRAN (ISLAMIC REPUBLIC OF)','Iranian Rial','IRR','364')
insert into aims_currency values ('INTERNATIONAL MONETARY FUND (IMF) ','SDR (Special Drawing Right)','XDR','960')
insert into aims_currency values ('INDONESIA','Rupiah','IDR','360')
insert into aims_currency values ('INDIA','Indian Rupee','INR','356')
insert into aims_currency values ('ICELAND','Iceland Krona','ISK','352')
insert into aims_currency values ('HUNGARY','Forint','HUF','348')
insert into aims_currency values ('HONG KONG','Hong Kong Dollar','HKD','344')
insert into aims_currency values ('HONDURAS','Lempira','HNL','340')
insert into aims_currency values ('HOLY SEE (THE)','Euro','EUR','978')
insert into aims_currency values ('HEARD ISLAND AND McDONALD ISLANDS','Australian Dollar','AUD','36')
insert into aims_currency values ('HAITI','Gourde','HTG','332')
insert into aims_currency values ('HAITI','US Dollar','USD','840')
insert into aims_currency values ('GUYANA','Guyana Dollar','GYD','328')
insert into aims_currency values ('GUINEA-BISSAU','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('GUINEA','Guinea Franc','GNF','324')
insert into aims_currency values ('GUERNSEY','Pound Sterling','GBP','826')
insert into aims_currency values ('GUATEMALA','Quetzal','GTQ','320')
insert into aims_currency values ('GUAM','US Dollar','USD','840')
insert into aims_currency values ('GUADELOUPE','Euro','EUR','978')
insert into aims_currency values ('GRENADA','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('GREENLAND','Danish Krone','DKK','208')
insert into aims_currency values ('GREECE','Euro','EUR','978')
insert into aims_currency values ('GIBRALTAR','Gibraltar Pound','GIP','292')
insert into aims_currency values ('GHANA','Ghana Cedi','GHS','936')
insert into aims_currency values ('GERMANY','Euro','EUR','978')
insert into aims_currency values ('GEORGIA','Lari','GEL','981')
insert into aims_currency values ('GAMBIA (THE)','Dalasi','GMD','270')
insert into aims_currency values ('GABON','CFA Franc BEAC','XAF','950')
insert into aims_currency values ('FRENCH SOUTHERN TERRITORIES (THE)','Euro','EUR','978')
insert into aims_currency values ('FRENCH POLYNESIA','CFP Franc','XPF','953')
insert into aims_currency values ('FRENCH GUIANA','Euro','EUR','978')
insert into aims_currency values ('FRANCE','Euro','EUR','978')
insert into aims_currency values ('FINLAND','Euro','EUR','978')
insert into aims_currency values ('FIJI','Fiji Dollar','FJD','242')
insert into aims_currency values ('FAROE ISLANDS (THE)','Danish Krone','DKK','208')
insert into aims_currency values ('FALKLAND ISLANDS (THE) [MALVINAS]','Falkland Islands Pound','FKP','238')
insert into aims_currency values ('EUROPEAN UNION','Euro','EUR','978')
insert into aims_currency values ('ETHIOPIA','Ethiopian Birr','ETB','230')
insert into aims_currency values ('ESTONIA','Euro','EUR','978')
insert into aims_currency values ('ERITREA','Nakfa','ERN','232')
insert into aims_currency values ('EQUATORIAL GUINEA','CFA Franc BEAC','XAF','950')
insert into aims_currency values ('EL SALVADOR','El Salvador Colon','SVC','222')
insert into aims_currency values ('EL SALVADOR','US Dollar','USD','840')
insert into aims_currency values ('EGYPT','Egyptian Pound','EGP','818')
insert into aims_currency values ('ECUADOR','US Dollar','USD','840')
insert into aims_currency values ('DOMINICAN REPUBLIC (THE)','Dominican Peso','DOP','214')
insert into aims_currency values ('DOMINICA','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('DJIBOUTI','Djibouti Franc','DJF','262')
insert into aims_currency values ('DENMARK','Danish Krone','DKK','208')
insert into aims_currency values ('CÔTE D''IVOIRE','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('CZECH REPUBLIC (THE)','Czech Koruna','CZK','203')
insert into aims_currency values ('CYPRUS','Euro','EUR','978')
insert into aims_currency values ('CURAÇAO','Netherlands Antillean Guilder','ANG','532')
insert into aims_currency values ('CUBA','Peso Convertible','CUC','931')
insert into aims_currency values ('CUBA','Cuban Peso','CUP','192')
insert into aims_currency values ('CROATIA','Kuna','HRK','191')
insert into aims_currency values ('COSTA RICA','Costa Rican Colon','CRC','188')
insert into aims_currency values ('COOK ISLANDS (THE)','New Zealand Dollar','NZD','554')
insert into aims_currency values ('CONGO (THE)','CFA Franc BEAC','XAF','950')
insert into aims_currency values ('CONGO (THE DEMOCRATIC REPUBLIC OF THE)','Congolese Franc','CDF','976')
insert into aims_currency values ('COMOROS (THE)','Comoro Franc','KMF','174')
insert into aims_currency values ('COLOMBIA','Colombian Peso','COP','170')
insert into aims_currency values ('COLOMBIA','Unidad de Valor Real','COU','970')
insert into aims_currency values ('COCOS (KEELING) ISLANDS (THE)','Australian Dollar','AUD','36')
insert into aims_currency values ('CHRISTMAS ISLAND','Australian Dollar','AUD','36')
insert into aims_currency values ('CHINA','Yuan Renminbi','CNY','156')
insert into aims_currency values ('CHILE','Unidad de Fomento','CLF','990')
insert into aims_currency values ('CHILE','Chilean Peso','CLP','152')
insert into aims_currency values ('CHAD','CFA Franc BEAC','XAF','950')
insert into aims_currency values ('CENTRAL AFRICAN REPUBLIC (THE)','CFA Franc BEAC','XAF','950')
insert into aims_currency values ('CAYMAN ISLANDS (THE)','Cayman Islands Dollar','KYD','136')
insert into aims_currency values ('CANADA','Canadian Dollar','CAD','124')
insert into aims_currency values ('CAMEROON','CFA Franc BEAC','XAF','950')
insert into aims_currency values ('CAMBODIA','Riel','KHR','116')
insert into aims_currency values ('CABO VERDE','Cabo Verde Escudo','CVE','132')
insert into aims_currency values ('BURUNDI','Burundi Franc','BIF','108')
insert into aims_currency values ('BURKINA FASO','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('BULGARIA','Bulgarian Lev','BGN','975')
insert into aims_currency values ('BRUNEI DARUSSALAM','Brunei Dollar','BND','96')
insert into aims_currency values ('BRITISH INDIAN OCEAN TERRITORY (THE)','US Dollar','USD','840')
insert into aims_currency values ('BRAZIL','Brazilian Real','BRL','986')
insert into aims_currency values ('BOUVET ISLAND','Norwegian Krone','NOK','578')
insert into aims_currency values ('BOTSWANA','Pula','BWP','72')
insert into aims_currency values ('BOSNIA AND HERZEGOVINA','Convertible Mark','BAM','977')
insert into aims_currency values ('BONAIRE, SINT EUSTATIUS AND SABA','US Dollar','USD','840')
insert into aims_currency values ('BOLIVIA (PLURINATIONAL STATE OF)','Boliviano','BOB','68')
insert into aims_currency values ('BOLIVIA (PLURINATIONAL STATE OF)','Mvdol','BOV','984')
insert into aims_currency values ('BHUTAN','Ngultrum','BTN','64')
insert into aims_currency values ('BHUTAN','Indian Rupee','INR','356')
insert into aims_currency values ('BERMUDA','Bermudian Dollar','BMD','60')
insert into aims_currency values ('BENIN','CFA Franc BCEAO','XOF','952')
insert into aims_currency values ('BELIZE','Belize Dollar','BZD','84')
insert into aims_currency values ('BELGIUM','Euro','EUR','978')
insert into aims_currency values ('BELARUS','Belarussian Ruble','BYR','974')
insert into aims_currency values ('BARBADOS','Barbados Dollar','BBD','52')
insert into aims_currency values ('BANGLADESH','Taka','BDT','50')
insert into aims_currency values ('BAHRAIN','Bahraini Dinar','BHD','48')
insert into aims_currency values ('BAHAMAS (THE)','Bahamian Dollar','BSD','44')
insert into aims_currency values ('AZERBAIJAN','Azerbaijanian Manat','AZN','944')
insert into aims_currency values ('AUSTRIA','Euro','EUR','978')
insert into aims_currency values ('AUSTRALIA','Australian Dollar','AUD','36')
insert into aims_currency values ('ARUBA','Aruban Florin','AWG','533')
insert into aims_currency values ('ARMENIA','Armenian Dram','AMD','51')
insert into aims_currency values ('ARGENTINA','Argentine Peso','ARS','32')
insert into aims_currency values ('ANTIGUA AND BARBUDA','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('ANTARCTICA','No universal currency','','')
insert into aims_currency values ('ANGUILLA','East Caribbean Dollar','XCD','951')
insert into aims_currency values ('ANGOLA','Kwanza','AOA','973')
insert into aims_currency values ('ANDORRA','Euro','EUR','978')
insert into aims_currency values ('AMERICAN SAMOA','US Dollar','USD','840')
insert into aims_currency values ('ALGERIA','Algerian Dinar','DZD','12')
insert into aims_currency values ('ALBANIA','Lek','ALL','8')
insert into aims_currency values ('AFGHANISTAN','Afghani','AFN','971')
