USE [AIMS_UPDATES]
GO

/****** Object:  Table [dbo].[AIMS_AA_DETAILS]    Script Date: 03/23/2019 16:46:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AIMS_AA_DETAILS](
	[AAID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[PATIENT_ID] [numeric](18, 0) NULL,
	[YELLOW_FEVER_CERTIFICATE] [varchar](250) NULL,
	[WEIGHTHEIGHTESTIMATE] [varchar](250) NULL,
	[REFERRING_HOSPITAL_NAME_LOCATION] [varchar](250) NULL,
	[REFERRING_HOSPITAL_TEL_NO] [varchar](250) NULL,
	[REFERRING_HOSPITAL_EMAIL] [varchar](250) NULL,
	[REFERRING_DOCTOR_NAME] [varchar](250) NULL,
	[REFERRING_DOCTOR_TEL_NO] [varchar](250) NULL,
	[REFERRING_DOCTOR_EMAIL] [varchar](250) NULL,
	[COMPANY_MEM_NAME] [varchar](250) NULL,
	[COMPANY_MEM_NATIONALITY] [varchar](250) NULL,
	[COMPANY_MEM_PASSPORT_NO] [varchar](250) NULL,
	[COMPANY_MEM_YELLOW_FEVER_CERT] [varchar](250) NULL,
	[VHFFORMREQUIREDYN] [varchar](1) NULL,
	[LOADED_BY] [varchar](50) NULL,
	[CREATION_DTTM] [datetime] NULL,
	[AA_POD] [varchar](500) NULL,
	[ACTIVE_YN] [varchar](1) NULL,
	[PATIENT_PASSPORT_NUMBER] [varchar](50) NULL,
	[COMPANY_MEM_WEIGHT_HEIGHT] [varchar](50) NULL,
	[AA_ADDRESS_TO] [varchar](250) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AIMS_AA_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_AIMS_AA_DETAILS_AIMS_PATIENT] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[AIMS_PATIENT] ([PATIENT_ID])
GO

ALTER TABLE [dbo].[AIMS_AA_DETAILS] CHECK CONSTRAINT [FK_AIMS_AA_DETAILS_AIMS_PATIENT]
GO

ALTER TABLE [dbo].[AIMS_AA_DETAILS] ADD  CONSTRAINT [DF_AIMS_AA_DETAILS_CREATIN_DTTM]  DEFAULT (getdate()) FOR [CREATION_DTTM]
GO

ALTER TABLE [dbo].[AIMS_AA_DETAILS] ADD  CONSTRAINT [DF_AIMS_AA_DETAILS_ACTIVE_YN]  DEFAULT ('Y') FOR [ACTIVE_YN]
GO

