alter proc AIMS_AADETAILS_ADD    
@PatientID varchar(50),    
@PatientYellowFeverCert varchar(50),    
@PatientWeightHeight varchar(50),    
@RefHosNameLocation varchar(50),    
@RefHosTel varchar(50),    
@RefHosEmail varchar(50),    
@RefHosDrName varchar(50),    
@RefHosDrNameTel varchar(50),    
@RefHosDrNameEmail varchar(50),    
@AccomMemNameSur varchar(50),    
@AccomMemNationality varchar(50),    
@AccomMemPassportNo varchar(50),    
@AccomMemYelFeverCert varchar(50),    
@AccomMemWeightHeight  varchar(50),    
@VHFFormRequiredYN varchar(1),    
@UserId varchar(50),  
@AirAmbulanceCELetter varchar(500),
@PatientPassportNo varchar(50),
@AAAddressToName  varchar(250)
as     
begin    
 insert into AIMS_AA_DETAILS(    
    PATIENT_ID,    
    YELLOW_FEVER_CERTIFICATE,    
    WEIGHTHEIGHTESTIMATE,    
    REFERRING_HOSPITAL_NAME_LOCATION,    
    REFERRING_HOSPITAL_TEL_NO,    
    REFERRING_HOSPITAL_EMAIL,    
    REFERRING_DOCTOR_NAME,    
    REFERRING_DOCTOR_TEL_NO,    
    REFERRING_DOCTOR_EMAIL,    
    COMPANY_MEM_NAME,    
    COMPANY_MEM_NATIONALITY,    
    COMPANY_MEM_PASSPORT_NO,    
    COMPANY_MEM_YELLOW_FEVER_CERT,    
    COMPANY_MEM_WEIGHT_HEIGHT,
    VHFFORMREQUIREDYN,    
    LOADED_BY , AA_POD  ,
    PATIENT_PASSPORT_NUMBER,
    AA_ADDRESS_TO
 ) values(    
 @PatientID ,    
 @PatientYellowFeverCert ,    
 @PatientWeightHeight ,    
 @RefHosNameLocation ,    
 @RefHosTel ,    
 @RefHosEmail ,    
 @RefHosDrName ,    
 @RefHosDrNameTel ,    
 @RefHosDrNameEmail ,    
 @AccomMemNameSur ,    
 @AccomMemNationality ,    
 @AccomMemPassportNo ,    
 @AccomMemYelFeverCert ,
 @AccomMemWeightHeight,    
 @VHFFormRequiredYN ,    
 @UserId   , @AirAmbulanceCELetter  , @PatientPassportNo,
 @AAAddressToName
 )    
end