USE [AIMS_UPDATES]
GO

/****** Object:  Table [dbo].[AIMS_AA_OPTIONS]    Script Date: 03/23/2019 16:50:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AIMS_AA_OPTIONS](
	[AAOPTION_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[AIRCRAFT] [varchar](50) NULL,
	[AVAILIBITY] [varchar](50) NULL,
	[COST] [varchar](50) NULL,
	[LEVELOFCARE] [varchar](50) NULL,
	[ROUTING] [varchar](50) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[PATIENT_ID] [numeric](18, 0) NULL,
	[CREATION_DTTM] [datetime] NULL,
	[ADMIN_FEE] [varchar](50) NULL,
	[AMBULANCE_REFERRING] [varchar](150) NULL,
	[AMBULANCE_RECEIVING] [varchar](150) NULL,
	[AIRPORT_OPERATING_HOURS] [varchar](50) NULL,
 CONSTRAINT [PK_AIMS_AA_OPTIONS] PRIMARY KEY CLUSTERED 
(
	[AAOPTION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AIMS_AA_OPTIONS]  WITH CHECK ADD  CONSTRAINT [FK_AIMS_AA_OPTIONS_AIMS_PATIENT] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[AIMS_PATIENT] ([PATIENT_ID])
GO

ALTER TABLE [dbo].[AIMS_AA_OPTIONS] CHECK CONSTRAINT [FK_AIMS_AA_OPTIONS_AIMS_PATIENT]
GO

ALTER TABLE [dbo].[AIMS_AA_OPTIONS] ADD  CONSTRAINT [DF_AIMS_AA_OPTIONS_CREATION_DTTM]  DEFAULT (getdate()) FOR [CREATION_DTTM]
GO

