CREATE TABLE [dbo].[AIMS_JOB_TITLE](
	[JOB_TITLE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[JOB_TITLE_DESC] [varchar](150) NULL,
 CONSTRAINT [PK_AIMS_JOB_TITLE] PRIMARY KEY CLUSTERED 
(
	[JOB_TITLE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[AIMS_DEPARTMENT](
	[DEPARTMENT_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[DEPARTMENT_NAME] [varchar](50) NULL,
	[DEPARTMENT_SUPERVISOR_USER_NAME] [varchar](50) NULL,
	[DEPARTMENT_MANAGER_USER_NAME] [varchar](50) NULL,
	[DEPARTMENT_EMAIL_ADDRESS] [varchar](150) NULL,
 CONSTRAINT [PK_AIMS_DEPARTMENT] PRIMARY KEY CLUSTERED 
(
	[DEPARTMENT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

