insert into aims_job_title values('Accounts Manager')
insert into aims_job_title values('Admin Assessor / Clerk')
insert into aims_job_title values('Admin Assessor')
insert into aims_job_title values('Admin Manager')
insert into aims_job_title values('Aeromedical Assistance Specialist')
insert into aims_job_title values('AIMS Legacy System Admin')
insert into aims_job_title values('Billings Clerk')
insert into aims_job_title values('Case Manager')
insert into aims_job_title values('Chief Executive Officer')
insert into aims_job_title values('Chief Financial Officer')
insert into aims_job_title values('Dispatch Clerk')
insert into aims_job_title values('Filing Assistant')
insert into aims_job_title values('Finance Administrator')
insert into aims_job_title values('General Manager')
insert into aims_job_title values('International Assistance Co-ordinator')
insert into aims_job_title values('International Assistance Specialist')
insert into aims_job_title values('Logistics and Compliance Officer')
insert into aims_job_title values('Network Manager Assistance')
insert into aims_job_title values('Network Manager')
insert into aims_job_title values('Operations Co-ordinator')
insert into aims_job_title values('Operations Coordinator')
insert into aims_job_title values('Senior Bookkeeper')
insert into aims_job_title values('Senior Operations Manager')
insert into aims_job_title values('Team Leader')
insert into aims_job_title values('Training, Logistics & Compliance Officer')