insert into aims_department(department_name) values('Billings')
insert into aims_department(department_name) values('Finance Department')
insert into aims_department(department_name) values('Finance')
insert into aims_department(department_name) values('IT')
insert into aims_department(department_name) values('Logistics and Compliance')
insert into aims_department(department_name) values('Operations')