UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='ALICEE'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='DANIELM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='DOMINICB'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='ELTONP'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='JADEP'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='NOMBUSOD'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='ROSEM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='NOKUTHULAM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='PRETTYR'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='SYLVIAD'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='JUAN-DREB'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='JABULANID'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='JACQUELINEA'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='LEIGH-ANN'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='MARDIAJ'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='MATTHEWH'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='MBALIS'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='GETRUDES'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='HORACIOR'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='CANDICED'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Billings') where user_name  ='CYNTHIAM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Finance') where user_name  ='HEATHERS'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Finance') where user_name  ='MZWANDILEM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Finance') where user_name  ='LAYLAD'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Finance') where user_name  ='VANESSAA'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Finance Department') where user_name  ='DOUGLASO'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'IT') where user_name  ='BRIAN'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Logistics and Compliance') where user_name  ='MATTHEW'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='LMOLEFE'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='LOLA'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='NELSAC'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='NICOLAM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='MIRRIAMP'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='LEBOHANGM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='KRISTELN'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='KRISTENM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='AIMS ANGELS'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='DANIELLEC'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='ARTHURB'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='BERNADETTEB'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='BIANCAK'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='BRAVEN'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='ERICP'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='GHOST RIDERS'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='HAROLDB'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='VICTORINOM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='VINOLIAE'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='VITAL VICTORS'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='WILLIAMF'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='SIPHESIHLEN'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='STANLEYN'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='TEAM TRIAGE'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='TEBELLOM'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='THULA'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='THULILEN'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='TUMELOT'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='REHAB ROCKSTARS'
UPDATE aims_users set department_id = (select department_id from aims_department where department_name = 'Operations') where user_name  ='NOMPUMELELOM'