select  
'update aims_users set job_title_id = ' + cast(a.job_title_id as varchar(50)) + ' where user_name= ''' +user_name ++''''
--job_title_id , JOB_TITLE_DESC 
from AIMS_JOB_TITLE a, aims_users b 
where b.job_title = a.job_title_desc
order by 1

update aims_users set job_title_id = 1 where user_name= 'DOUGLASO'
update aims_users set job_title_id = 10 where user_name= 'HEATHERS'
update aims_users set job_title_id = 11 where user_name= 'ROSEM'
update aims_users set job_title_id = 12 where user_name= 'NOKUTHULAM'
update aims_users set job_title_id = 12 where user_name= 'PRETTYR'
update aims_users set job_title_id = 13 where user_name= 'LAYLAD'
update aims_users set job_title_id = 13 where user_name= 'MZWANDILEM'
update aims_users set job_title_id = 14 where user_name= 'JADEP'
update aims_users set job_title_id = 15 where user_name= 'NATHANIELT'
update aims_users set job_title_id = 16 where user_name= 'ALBINO'
update aims_users set job_title_id = 16 where user_name= 'ARTHURB'
update aims_users set job_title_id = 16 where user_name= 'CARLOSJ'
update aims_users set job_title_id = 16 where user_name= 'DANIELLEC'
update aims_users set job_title_id = 16 where user_name= 'LOLA'
update aims_users set job_title_id = 16 where user_name= 'SARAHM'
update aims_users set job_title_id = 16 where user_name= 'SUSAN'
update aims_users set job_title_id = 16 where user_name= 'TEBELLOM'
update aims_users set job_title_id = 16 where user_name= 'VANESSAN'
update aims_users set job_title_id = 16 where user_name= 'WILLIAMF'
update aims_users set job_title_id = 17 where user_name= 'DANIELM'
update aims_users set job_title_id = 17 where user_name= 'HUGOM'
update aims_users set job_title_id = 18 where user_name= 'KRISTENM'
update aims_users set job_title_id = 19 where user_name= 'ERICP'
update aims_users set job_title_id = 2 where user_name= 'CANDICED'
update aims_users set job_title_id = 2 where user_name= 'MATTHEWH'
update aims_users set job_title_id = 20 where user_name= 'AIMS ANGELS'
update aims_users set job_title_id = 20 where user_name= 'BIANCAK'
update aims_users set job_title_id = 20 where user_name= 'BRAVEN'
update aims_users set job_title_id = 20 where user_name= 'GHOST RIDERS'
update aims_users set job_title_id = 20 where user_name= 'KRISTELN'
update aims_users set job_title_id = 20 where user_name= 'LEBOHANGM'
update aims_users set job_title_id = 20 where user_name= 'LMOLEFE'
update aims_users set job_title_id = 20 where user_name= 'NELSAC'
update aims_users set job_title_id = 20 where user_name= 'NOMPUMELELOM'
update aims_users set job_title_id = 20 where user_name= 'REHAB ROCKSTARS'
update aims_users set job_title_id = 20 where user_name= 'SIPHESIHLEN'
update aims_users set job_title_id = 20 where user_name= 'TEAM TRIAGE'
update aims_users set job_title_id = 20 where user_name= 'THULILEN'
update aims_users set job_title_id = 20 where user_name= 'TUMELOT'
update aims_users set job_title_id = 20 where user_name= 'VINOLIAE'
update aims_users set job_title_id = 20 where user_name= 'VITAL VICTORS'
update aims_users set job_title_id = 21 where user_name= 'JKYRIACOS'
update aims_users set job_title_id = 21 where user_name= 'MIRRIAMP'
update aims_users set job_title_id = 21 where user_name= 'VICTORINOM'
update aims_users set job_title_id = 22 where user_name= 'VANESSAA'
update aims_users set job_title_id = 23 where user_name= 'STANLEYN'
update aims_users set job_title_id = 24 where user_name= 'NICOLAM'
update aims_users set job_title_id = 25 where user_name= 'MATTHEW'
update aims_users set job_title_id = 3 where user_name= 'CYNTHIAM'
update aims_users set job_title_id = 3 where user_name= 'GETRUDES'
update aims_users set job_title_id = 3 where user_name= 'HORACIOR'
update aims_users set job_title_id = 3 where user_name= 'JABULANID'
update aims_users set job_title_id = 3 where user_name= 'JACQUELINEA'
update aims_users set job_title_id = 3 where user_name= 'JUAN-DREB'
update aims_users set job_title_id = 4 where user_name= 'CHARLAINE'
update aims_users set job_title_id = 5 where user_name= 'HAROLDB'
update aims_users set job_title_id = 5 where user_name= 'THULA'
update aims_users set job_title_id = 6 where user_name= 'BRIAN'
update aims_users set job_title_id = 7 where user_name= 'LEIGH-ANN'
update aims_users set job_title_id = 7 where user_name= 'MARDIAJ'
update aims_users set job_title_id = 7 where user_name= 'MBALIS'
update aims_users set job_title_id = 7 where user_name= 'SYLVIAD'
update aims_users set job_title_id = 8 where user_name= 'DOMINICB'
update aims_users set job_title_id = 9 where user_name= 'BERNADETTEB'